# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FocusArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('detail', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=200)),
                ('img', models.ImageField(upload_to='focus_areas/')),
            ],
        ),
        migrations.CreateModel(
            name='NSICInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.TextField(max_length=1000)),
                ('details', models.TextField(max_length=1000)),
                ('logo', models.ImageField(upload_to='')),
                ('focus_areas', models.ManyToManyField(to='nsic.FocusArea')),
            ],
            options={
                'verbose_name_plural': 'NSIC Info',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='company_logos/')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='company_logos/')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(default=False)),
                ('day1', models.DateField()),
                ('day2', models.DateField()),
                ('registration_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('possible_topics', models.URLField()),
                ('sign_up_form', models.URLField()),
                ('individual_form', models.URLField()),
                ('volunteer_form', models.URLField()),
                ('mailchimp', models.URLField()),
                ('fb_event', models.URLField()),
                ('day1_schedule', models.ManyToManyField(related_name='day1_schedule', to='nsic.ScheduleItem')),
                ('day2_schedule', models.ManyToManyField(related_name='day2_schedule', to='nsic.ScheduleItem')),
                ('partners', models.ManyToManyField(to='nsic.Partner')),
                ('prizes', models.ManyToManyField(to='nsic.Prize')),
                ('sponsors', models.ManyToManyField(to='nsic.Sponsor')),
            ],
        ),
    ]
