# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Built-It-Night'), (2, 'Tech Talk')], default='1')),
                ('title', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=100)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('description', models.CharField(max_length=10000)),
                ('steam_url', models.URLField()),
                ('docs', models.ManyToManyField(to='main.Docs')),
            ],
        ),
    ]
