# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170811_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=10000),
        ),
    ]
