# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170811_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='eboard',
            name='term',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
