# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_eboard_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('club_page', models.URLField()),
                ('twitter', models.URLField()),
                ('facebook', models.URLField()),
            ],
            options={
                'verbose_name': 'Club Info',
            },
        ),
    ]
